### ISSUE TITLE
new version won't run on winXP

### ISSUE THREAD

**Issue by JPDoch** [basildane/WakeOnLAN#13] opened 2016-05-08 07:42 UTC
On a winXP 32bit machine I just upgraded to the latest version 2.11.9 and I get an error "wakeonlan.exe is not a valid win32 applictation".  Downgraded back to 2.11.4 and it works fine.

**Comment by basildane** [comment] 2016-05-08 14:38
I no longer have any 32 bit machines. I am going to build a 32 bit machine today to test with.

**Comment by JPDoch** [comment] 2016-05-08 15:15
I have one 32bit machine left as a sort of web server.  It's not a 
problem for me, I can use one of my other 64bit machines, I just thought 
I'd let you know.

In any case, your WakeOnLan is brilliant!

**Comment by basildane** [comment] 2016-05-08 15:22
Thanks for the encouragement!
There are lots of folks still on 32 bit in other counties, so I really need to get on that.  I appreciate your letting me know.

**Comment by basildane** [comment] 2016-05-08 23:43
I have built a Win 10 x86 Home workgroup test machine.  It worked perfectly.
Then I built an XP x86 Pro machine.  Then I got the same error you reported.

So, it's an XP issue, not a 32 bit issue.  No idea what the problem is yet.

**Comment by JPDoch** [comment] 2016-05-09 06:41
You're right, the machine I had the problem with is XPpro 32 bit.

**Comment by basildane** [comment] 2016-05-09 12:07
The problem is that the newer versions are running DotNet 4.6.  XP doesn't seem to support that.  I am not sure how you are even running XP as I cannot even get it to activate.  I tried to update IE to the latest version and it just says "time to upgrade your operating system" and it kicks me out.  If you can figure out a way to download 4.6 let me know, XP won't even display the web page on Microsoft's site.  XP pro sp3.

**Comment by JPDoch** [comment] 2016-05-09 12:19
I believe they stopped supporting Net framework on XP with version 4.5.

https://blogs.msdn.microsoft.com/dotnet/p/dotnet45xp/

the machine I was running on has 4.0 installed which I think is the last 
one that worked.

As I said not a big deal for me (although as you say, you might get 
problems from other countries) but I'm a bit mystified as to why you 
found it would run on XP 32bit but not XP pro 32bit as I believe they 
both have the same limitations as to .Net

Idle curiousity only, of course.

I guess you could just flag on the download page which versions work 
with XP and which don't.  Where I got caught was I let WakeOnLan do it's 
own automatic upgrade, so I guess you'd have to put a prompt in that 
saying not to upgrade if running on XP, maybe.  Good luck with it, anyway.

**Comment by basildane** [comment] 2016-05-09 12:28
No, I built a Windows 10 x86 home machine and that worked.  It did not work with XP.
Versions of WOL prior to 2.11.5 used Dotnet 4.0, so those should still work.

**Comment by basildane** [comment] 2016-05-09 12:29
Yes, I will update the web page and installer soon.  Thanks.

**Comment by basildane** [comment] 2016-05-10 14:11
I am updating the Help page and closing issue.

**Comment by basildane** [comment] 2016-05-18 14:37
New build [beta-15](https://github.com/basildane/WakeOnLAN/releases/tag/2.11.9-beta.15).
This should work on XP and 2003 server.

**Closed** 2016-07-05 12:46 UTC
