### ISSUE TITLE
Crash when creating new host

### ISSUE THREAD

**Issue by zdaar** [basildane/WakeOnLAN#73] opened 2017-06-23 10:23 UTC
Hello, 

Program crashes when attempting to create a new host after fresh install of the program on windows 10 creator's upate.

Stack trace 

   at WakeOnLan.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at WakeOnLan.Explorer.NewToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by basildane** [comment] 2017-06-23 17:28
I just built a completely fresh Win 10 machine as you described, and confirmed the error.  I am investigating.

**Comment by basildane** [comment] 2017-06-24 02:15
Fixed.  This will be in the next release.  The problem was the encryption library was not initialized properly.  Thanks for reporting it.

**Closed by basildane** 2017-06-24 02:15 UTC
Labels: bug

**Comment by zdaar** [comment] 2017-06-24 02:31
Hello,

Amazing !

Good work thanks for your time :)

2017-06-24 4:15 GMT+02:00 Basildane <notifications@github.com>:

**Comment by basildane** [comment] 2017-06-24 15:21
You are welcome.  I forgot to post a link to the beta build if you wanted to try it, or needed it.
[Beta 2.11.17.29](https://cloud.aquilatech.com/s/bTGFTJcQ2WhPsDA)

It is not signed, but it is fully functional.
