### ISSUE TITLE
WOL keeps notifying (looping)

### ISSUE THREAD

**Issue by AntoniusFM** [basildane/WakeOnLAN#69] opened 2017-06-07 01:43 UTC
Hi there,

I love your program, but i have got a strange issue, for some reason it keeps notifying that the host is online and offline, every couple of seconds, even though there is no change on the host See attached screenprint of the log file. I have installed WOL on a few PC's, and it seems this behaviour is showing on all the PC's i have got WOL installed on. What could be the reason of this ?
![wakonlanissue](https://user-images.githubusercontent.com/29242075/26858748-74f90afa-4b76-11e7-8c3c-9c141c51174b.jpg)

**Comment by basildane** [comment] 2017-06-07 14:27
I have seen this problem myself, on rare occasions, and I haven't found the cause yet.

If you highlight the host (click on it), it will show the "response time" in the status bar on the bottom of WOL.  What is the response time to this host?

Also, how many hosts do you have configured?

Is this host on the same network as you?  Same subnet?

**Comment by AntoniusFM** [comment] 2017-06-14 00:26
Sorry for the slow response.
This is happening on completely different networks, and the hosts are on
the same network, not subnets involved.
What i am trying to say is that this behaviour happens on networks not
related to each other, but i am using the same version of your WakeOnLan.
I have configured on a small amount of hosts in this case only one, i have
attached a few screen-dumps of the different response times.

[image: Inline image 1]
[image: Inline image 2]
[image: Inline image 4]

In this particular situation i am accessing the computer (server) running
the WakeOnLan software via an RDP session, but the problem also happens on
situations where no RDP is involved.

Hope this helps.

Kind regards.

**Comment by basildane** [comment] 2017-06-14 00:32
images did not come through.

**Comment by AntoniusFM** [comment] 2017-06-14 00:50
OK hopefully this will work

**Comment by AntoniusFM** [comment] 2017-06-14 00:56
I was replying via email, so that's maybe why the attachments didn't came through.
![image](https://user-images.githubusercontent.com/29242075/27110910-ee9c884a-50ef-11e7-9ccb-3fec7be5fea6.png)
![image](https://user-images.githubusercontent.com/29242075/27110914-f433c1e2-50ef-11e7-8a92-1ca964a6d4c7.png)
![image](https://user-images.githubusercontent.com/29242075/27110928-06eb3b08-50f0-11e7-95de-2bad1b71ce06.png)

**Comment by basildane** [comment] 2017-06-15 16:21
I've been running a wireshark capture and monitoring this for 5 hours now and it has not blipped once.  Still trying to reproduce it.

**Comment by basildane** [comment] 2017-06-15 16:46
Even though I have not reproduced the error, I have been looking at that function and I see some suspect code that COULD possibly cause this.  I need some time, but I'll build a test case.

**Comment by AntoniusFM** [comment] 2017-06-19 00:12
Thanks for reply, it doesn't always happen, but if it happens it's constantly, the only way to stop it, is to stop WakeUpLan. It seems to happen more frequently (not always though) when returning to a previous hibernated session. Hope this helps.

**Comment by basildane** [comment] 2017-06-19 13:28
I have a beta version that I need you to test with please.
You can download it [here](https://cloud.aquilatech.com/s/eiOcCDD4r7rC881).
Just extract the two files to your \Program Files\Aquila Technology\WakeOnLAN folder.

When you run the program, click once to highlight the machine that is flapping.  An error message will be displayed in the status bar, I need that.

Thanks.

**Comment by basildane** [comment] 2017-06-19 13:30
I think there is an unhandled exception in the TCP functions, and while I think I caught it in the above beta, I want to make absolutely sure, and also I'm curious what the exception is at your end.

**Comment by AntoniusFM** [comment] 2017-06-21 06:44
OK done what you requested (sorry for the delay). Still that same problem, and i had to double click, on the machine which was causing the issue, see the attached screen prints.
![wakeonlan1](https://user-images.githubusercontent.com/29242075/27370633-c62a0caa-56a0-11e7-98e3-ac2e8eb98533.jpg)
![wakeonlan2](https://user-images.githubusercontent.com/29242075/27370640-ce9a76c2-56a0-11e7-96f4-7a88da0ade7c.jpg)
![wakeonlan3](https://user-images.githubusercontent.com/29242075/27370648-d5123698-56a0-11e7-8ae0-1e1633ea2148.jpg)

**Comment by basildane** [comment] 2017-06-23 16:21
Thanks.  Sadly I did not capture the error, so here's another try.
This is [beta 2.11.17.25](https://cloud.aquilatech.com/s/KEQ0sHB9nmw0AL4)

If you would extract the program into your current program and run it, there is a new option.
Click on "View" then "Debug Log".  This is open a debug window and list each message WOL receives.  If you would capture a few entries for your host that is flapping and then copy it to me, it would be really helpful.

Sorry for all this work.  I really want to solve this one once and for all.
Thanks for your understanding.

**Comment by AntoniusFM** [comment] 2017-06-24 02:27
No worries happy to assist.
Anyway was about to install your latest beta files, when i noticed i had 2 installations on my surface 3 (win10), one in "Program Files" and one in "Program Files (x86), which can't be correct ? Could this have happened after an update, i don't have WakeOnLan in the default suggested dir ?

![doublewolinstall](https://user-images.githubusercontent.com/29242075/27504940-8ef7d12a-58d7-11e7-98a5-8ee99d5a94ae.jpg)
 
I also noticed several entries in the icons to appear within the taskbar (Win 10), it seems these are not cleaned-up after an uninstall.

![multipleiconsetuptaskbar](https://user-images.githubusercontent.com/29242075/27504963-e94c17a8-58d7-11e7-8621-3185bf2c8cdc.jpg)

I have uninstalled everything and reinstalled your latest version 2.11.16, then i installed your debug version on top of it. Guess what at the moment i can't seem to replicate the problem, but i'll keep testing and let you know when i have got more details.

**Comment by AntoniusFM** [comment] 2017-06-28 00:22
Ok more luck today, find below the debug log;

> 06/28/2017 09:33:04.531: Debug log started
06/28/2017 09:33:16.708: DesktopIT2: Success
06/28/2017 09:33:23.426: DesktopIT2: TimedOut
06/28/2017 09:33:25.467: DesktopIT2: Success
06/28/2017 09:33:32.413: DesktopIT2: TimedOut
06/28/2017 09:33:41.471: DesktopIT2: Success
06/28/2017 09:33:48.425: DesktopIT2: TimedOut
06/28/2017 09:34:05.991: DesktopIT2: Success
06/28/2017 09:34:16.935: DesktopIT2: TimedOut
06/28/2017 09:34:27.357: DesktopIT2: Success
06/28/2017 09:34:33.906: DesktopIT2: TimedOut
06/28/2017 09:35:32.123: DesktopIT2: Success
06/28/2017 09:35:38.920: DesktopIT2: TimedOut
06/28/2017 09:36:24.531: DesktopIT2: Success
06/28/2017 09:36:35.407: DesktopIT2: TimedOut
06/28/2017 09:37:54.448: DesktopIT2: Success
06/28/2017 09:38:01.388: DesktopIT2: TimedOut
06/28/2017 09:38:34.567: DesktopIT2: Success
06/28/2017 09:38:41.432: DesktopIT2: TimedOut
06/28/2017 09:38:45.457: DesktopIT2: Success
06/28/2017 09:38:59.435: DesktopIT2: TimedOut
06/28/2017 09:39:05.087: DesktopIT2: Success
06/28/2017 09:40:15.422: DesktopIT2: TimedOut
06/28/2017 09:40:33.439: DesktopIT2: Success
06/28/2017 09:41:16.905: DesktopIT2: TimedOut
06/28/2017 09:41:21.708: DesktopIT2: Success
06/28/2017 09:41:52.416: DesktopIT2: TimedOut
06/28/2017 09:41:59.167: DesktopIT2: Success
06/28/2017 09:42:09.411: DesktopIT2: DestinationHostUnreachable
06/28/2017 09:42:23.456: DesktopIT2: Success
06/28/2017 09:42:47.404: DesktopIT2: TimedOut
06/28/2017 09:42:54.142: DesktopIT2: Success
06/28/2017 09:43:06.420: DesktopIT2: TimedOut
06/28/2017 09:43:12.391: DesktopIT2: Success
06/28/2017 09:43:18.944: DesktopIT2: TimedOut
06/28/2017 09:43:23.846: DesktopIT2: Success
06/28/2017 09:43:30.419: DesktopIT2: TimedOut
06/28/2017 09:43:37.163: DesktopIT2: Success
06/28/2017 09:43:49.434: DesktopIT2: TimedOut
06/28/2017 09:43:58.994: DesktopIT2: Success
06/28/2017 09:44:05.919: DesktopIT2: TimedOut
06/28/2017 09:44:12.203: DesktopIT2: Success
06/28/2017 09:44:32.420: DesktopIT2: TimedOut
06/28/2017 09:44:39.105: DesktopIT2: Success
06/28/2017 09:44:51.414: DesktopIT2: TimedOut
06/28/2017 09:44:58.173: DesktopIT2: Success
06/28/2017 09:45:25.906: DesktopIT2: DestinationHostUnreachable
06/28/2017 09:45:27.967: DesktopIT2: Success
06/28/2017 09:46:19.913: DesktopIT2: DestinationHostUnreachable
06/28/2017 09:46:26.941: DesktopIT2: Success
06/28/2017 09:47:19.911: DesktopIT2: DestinationHostUnreachable
06/28/2017 09:47:26.963: DesktopIT2: Success
06/28/2017 09:47:39.411: DesktopIT2: TimedOut
06/28/2017 09:47:46.111: DesktopIT2: Success
06/28/2017 09:48:28.431: DesktopIT2: TimedOut

**Comment by basildane** [comment] 2017-06-28 00:47
I'll comment on the multiple versions later, but right now, looking at this log, it is occasionally taking 10 - 30 seconds to ping DesktopIT2.  After 5 seconds, it is assumed the machine is off.  Do you have any ideas why the pings are delayed.

Second question, can you stop WOL program, open open a command prompt and ping the machine.  (when it is in a failure type attitude like this).  Do you still see the long ping times?

**Comment by AntoniusFM** [comment] 2017-06-28 02:17
No DestopIT2 is on, the problems only seems to happen when a host is on. Have no idea why thi=ses pngs are that long, normal pings doesn't seem to take that long.
![wolissue2](https://user-images.githubusercontent.com/29242075/27617781-b173ec94-5bfb-11e7-98b8-9f4b7c4b654a.jpg)

**Comment by AntoniusFM** [comment] 2017-06-28 02:23
pinging using the IP address

![wolissue3](https://user-images.githubusercontent.com/29242075/27617859-4fd3cb34-5bfc-11e7-93a3-802e7d8aef50.jpg)

**Comment by basildane** [comment] 2017-06-28 18:56
> I also noticed several entries in the icons to appear within the taskbar (Win 10), it seems these are not cleaned-up after an uninstall.

What happened is we made the application 64 bit native around that release.  Unfortunately, it did not uninstall the previous 32 bit version.  Sloppy, but would not cause any problems.  Going forward, this will not happen again.

**Comment by basildane** [comment] 2017-06-28 18:58
As for your  pings, I am scratching my head on this one.

**Comment by basildane** [comment] 2017-07-02 00:29
Just a quick update, the "5 second" delay is a red herring.  There is not an actual delay in the ping response, it was because the test purposely puts a delay between the packets to help not stress the network.

I'm still investigating.  Any news on your end?  Is the problem still occurring?  Any pattern?

**Comment by basildane** [comment] 2017-07-02 02:02
Wow, I think I have found the problem.  I just made a test case that proves there is a bug in the dotnet framework System.Net.NetworkInformation.Ping class.  And then I found other people reporting the exact same problem we are seeing here.  I should have a work-around soon.

**Comment by AntoniusFM** [comment] 2017-07-03 03:59
Hi, sorry no additional info. Well done on finding the dotnet bug. Cannot replicate the problem so far on my home network. Will post more info when i can replicate,

**Comment by basildane** [comment] 2017-07-03 16:06
This should now be fixed in [2.11.17-beta 30](https://github.com/basildane/WakeOnLAN/releases/tag/2.11.17-beta.30).
Full release coming out soon.  Thanks.

**Closed** 2017-07-31 10:56 UTC
Labels: bug
